[package]
name = "jj-tandem-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Remote jj store integration for Tandem clients"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
blake2.workspace = true
futures.workspace = true
jj-lib.workspace = true
jj-tandem-jj.workspace = true
jj-tandem-protocol.workspace = true
prost.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
