//! Generated schedules, and the loop that runs one.
//!
//! A schedule is a list of steps and a seed that produced it. Running it is
//! deterministic end to end: the same seed builds the same agents, the same
//! file contents, the same faults, in the same order. So a failure is not a
//! story about timing — it is a number, and the number reproduces it.

use anyhow::{Context, Result};
use jj_tandem::server::CrashWindow;

use super::agent::Agent;
use super::cluster::Cluster;
use super::oracle;
use super::rng::Rng;

/// The paths a schedule may touch. A short list on purpose: agents that never
/// pick the same path never produce the conflicts worth testing.
const PATHS: [&str; 5] = [
    "a.txt",
    "b.txt",
    "dir/c.txt",
    "dir/nested/d.bin",
    "README.md",
];

#[derive(Debug, Clone)]
pub enum Step {
    /// Write files into a new commit and publish it.
    Commit {
        agent: usize,
        files: Vec<(String, Vec<u8>)>,
        description: String,
    },
    /// Rewrite the working commit — the operation most likely to expose a
    /// lost update as a divergent change.
    Describe { agent: usize, description: String },
    /// Make the next `count` index writes look like compare-and-swap losses.
    ArmCasConflicts { count: u64 },
    /// Stand in for another writer whose object lands between two attempts of
    /// a retried publish.
    StageObjectOnConflict { bytes: Vec<u8> },
    /// Make the bucket refuse the next `count` WAL entries — the window in
    /// which a publish has drained the staging buffer and cannot store it.
    FailWalWrites { count: u64 },
    /// Make the bucket fail while the server writes a derived head's WAL entry.
    FailDerivedHeadWal(bool),
    /// Stop the next publish at a named point in the durability order.
    ArmCrash(CrashWindow),
    /// Take the server away and bring it back over the same durable state.
    Restart,
    /// Take the server away, throw its disk away too, and bring it back over
    /// the bucket alone.
    ColdRestart,
}

impl Step {
    /// A one-line name for a failure message. The full debug form would print
    /// every generated byte.
    pub fn label(&self) -> String {
        match self {
            Step::Commit { agent, files, .. } => {
                let paths: Vec<&str> = files.iter().map(|(path, _)| path.as_str()).collect();
                format!("agent{agent} commits {}", paths.join(", "))
            }
            Step::Describe { agent, .. } => format!("agent{agent} describes"),
            Step::ArmCasConflicts { count } => format!("arm {count} index CAS conflicts"),
            Step::StageObjectOnConflict { bytes } => {
                format!("stage a {}-byte object on the next conflict", bytes.len())
            }
            Step::FailWalWrites { count } => format!("make the next {count} WAL writes fail"),
            Step::FailDerivedHeadWal(on) => format!("derived-head WAL failure = {on}"),
            Step::ArmCrash(window) => format!("arm a crash at {}", window.as_str()),
            Step::Restart => "restart the server".to_string(),
            Step::ColdRestart => "restart the server from the bucket alone".to_string(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct Schedule {
    pub seed: u64,
    pub agent_count: usize,
    pub steps: Vec<Step>,
}

/// Build the schedule this seed names.
pub fn generate(seed: u64) -> Schedule {
    let mut rng = Rng::new(seed);
    let agent_count = rng.between(1, 3);
    let target_steps = rng.between(4, 12);

    let mut steps = Vec::new();
    while steps.len() < target_steps {
        let roll = rng.below(100);
        match roll {
            0..=52 => steps.push(commit_step(&mut rng, agent_count, steps.len())),
            53..=72 => steps.push(Step::Describe {
                agent: rng.below(agent_count),
                description: format!("described at step {}", steps.len()),
            }),
            73..=80 => {
                // Below the client's retry budget on purpose: this is a test
                // of the retry, not of giving up.
                steps.push(Step::ArmCasConflicts {
                    count: rng.between(1, 5) as u64,
                });
                steps.push(commit_step(&mut rng, agent_count, steps.len()));
            }
            81..=88 => {
                let window = *rng.pick(&CrashWindow::ALL);
                steps.push(Step::ArmCrash(window));
                // A crash that never fires tests nothing, so the publish that
                // trips it is part of the step.
                steps.push(commit_step(&mut rng, agent_count, steps.len()));
            }
            89..=90 => steps.push(Step::Restart),
            91..=92 => steps.push(Step::ColdRestart),
            93..=95 => {
                steps.push(Step::StageObjectOnConflict {
                    bytes: staged_object(&mut rng, steps.len()),
                });
                steps.push(Step::ArmCasConflicts { count: 1 });
                steps.push(commit_step(&mut rng, agent_count, steps.len()));
            }
            96..=97 => {
                // The publish this fails has already drained the staging
                // buffer. Whatever it took must come back out in a later entry.
                steps.push(Step::FailWalWrites {
                    count: rng.between(1, 3) as u64,
                });
                steps.push(commit_step(&mut rng, agent_count, steps.len()));
                steps.push(Step::FailWalWrites { count: 0 });
            }
            _ => {
                steps.push(Step::FailDerivedHeadWal(true));
                steps.push(commit_step(&mut rng, agent_count, steps.len()));
                steps.push(Step::FailDerivedHeadWal(false));
            }
        }
    }

    Schedule {
        seed,
        agent_count,
        steps,
    }
}

/// The content of an object a second writer lands mid-retry.
///
/// It carries a marker so that finding it in a WAL entry means finding *it*:
/// a handful of random bytes could turn up inside somebody else's file by
/// coincidence, and a check that can pass by coincidence is not a check.
pub fn staged_object(rng: &mut Rng, index: usize) -> Vec<u8> {
    let mut bytes = format!("tandem-object-written-between-retries-at-step-{index}-").into_bytes();
    let len = rng.between(16, 256);
    bytes.extend(rng.bytes(len));
    bytes
}

fn commit_step(rng: &mut Rng, agent_count: usize, index: usize) -> Step {
    let file_count = rng.between(1, 3);
    let mut files = Vec::new();
    for _ in 0..file_count {
        let path = (*rng.pick(&PATHS)).to_string();
        // Sizes that straddle the boundaries worth straddling: empty, a few
        // bytes, and past the point where a body stops being one small write.
        let len = match rng.below(10) {
            0 => 0,
            1..=6 => rng.between(1, 512),
            7..=8 => rng.between(512, 8 * 1024),
            _ => rng.between(8 * 1024, 96 * 1024),
        };
        let bytes = rng.bytes(len);
        if files.iter().any(|(existing, _)| *existing == path) {
            continue;
        }
        files.push((path, bytes));
    }
    if files.is_empty() {
        let len = rng.between(1, 64);
        files.push((PATHS[0].to_string(), rng.bytes(len)));
    }
    Step::Commit {
        agent: rng.below(agent_count),
        files,
        description: format!("commit at step {index}"),
    }
}

/// Run one schedule, checking every invariant after every step.
pub fn run(schedule: &Schedule) -> Result<()> {
    let mut cluster = Cluster::start().context("start the cluster")?;
    let mut agents = Vec::new();
    for index in 0..schedule.agent_count {
        agents.push(
            Agent::join(&cluster, &format!("agent{index}"))
                .with_context(|| format!("agent{index} joins"))?,
        );
    }
    oracle::check(&cluster, &agents, "setup")?;

    // Bytes this server took in that no WAL entry has carried yet. They are
    // checked at the end, not here, because the publish that has to carry them
    // is whichever one comes next — a retried publish cannot (its entry is
    // already in the bucket and immutable), and a failed one did not.
    //
    // "This server": the staging buffer is memory, deliberately. An object in
    // it belongs to a publish that has not been acknowledged, so a process that
    // dies holding it owes nobody anything — the client's operation failed and
    // it will write the objects again. The list is therefore dropped whenever
    // the server goes away, and what survives is the real invariant: while one
    // process lives, nothing it drained is lost.
    let mut owed_bytes: Vec<Vec<u8>> = Vec::new();
    // Whether a WAL-write failure is armed. A publish under one is expected to
    // fail, so the client error it produces is not the simulation's finding.
    let mut wal_writes_failing = false;

    for (number, step) in schedule.steps.iter().enumerate() {
        match step {
            Step::StageObjectOnConflict { bytes } => owed_bytes.push(bytes.clone()),
            Step::FailWalWrites { count } => wal_writes_failing = *count > 0,
            // The client wrote these objects to the server before it published.
            // The publish drained them and then could not store them, so
            // restaging is the only thing that keeps them.
            Step::Commit { files, .. } if wal_writes_failing => {
                owed_bytes.extend(files.iter().map(|(_, bytes)| bytes.clone()));
            }
            Step::Restart | Step::ColdRestart => owed_bytes.clear(),
            _ => {}
        }

        apply(&mut cluster, &mut agents, step, wal_writes_failing)
            .with_context(|| format!("step {number} ({})", step.label()))?;

        // A halted server is a dead process. Nothing else can happen until
        // something starts it again, so the schedule does.
        if cluster.halted() {
            cluster
                .restart()
                .with_context(|| format!("restart after step {number} ({})", step.label()))?;
            owed_bytes.clear();
        }

        oracle::check(&cluster, &agents, &format!("step {number} ({})", step.label()))?;
    }

    close(&mut cluster, &mut agents, &owed_bytes)
}

/// What every schedule ends with, whatever it did.
///
/// Two things the step loop cannot check on its own:
///
/// - An object the server took in but no entry carried — staged between two
///   attempts of a retried publish, or drained by a publish whose WAL write
///   then failed — is durable only once a *later* publish carries it. So the
///   check belongs after the last step rather than beside the step that armed
///   it. One closing publish gives every schedule that later publish, so the
///   check is the same whatever the schedule stopped on.
/// - The WAL is complete. Every restart so far kept the materialized repo, and
///   the server answers reads out of it, so an object that reached the server's
///   disk but no WAL entry is invisible: the whole suite passes while the only
///   durable copy of it does not exist. The last thing a schedule does is throw
///   that disk away and read everything back out of the bucket.
fn close(cluster: &mut Cluster, agents: &mut [Agent], owed_bytes: &[Vec<u8>]) -> Result<()> {
    // A fault belongs to the step that armed it. The closing publish is the
    // harness's, not the schedule's, so it runs against a healthy server.
    cluster.faults.set_index_cas_conflicts(0);
    cluster.faults.crash_at(None);
    cluster.faults.fail_derived_head_wal(false);
    cluster.faults.fail_wal_writes(0);
    cluster.faults.stage_object_on_index_conflict(None);

    if let Some(agent) = agents.first_mut() {
        agent
            .commit_files(
                &[(
                    "closing.txt".to_string(),
                    b"the publish that drains what is staged\n".to_vec(),
                )],
                "closing publish",
            )
            .context("the closing publish")?;
    }
    oracle::check(cluster, agents, "the closing publish")?;

    for bytes in owed_bytes {
        // Empty content is no object: there is nothing to look for, and every
        // byte string contains the empty one.
        if bytes.is_empty() {
            continue;
        }
        let head = String::from_utf8_lossy(&bytes[..bytes.len().min(48)]).into_owned();
        oracle::assert_bytes_in_some_wal_entry(
            cluster,
            bytes,
            &format!("an object the server took in but no publish carried ({head}…)"),
        )?;
    }

    cluster
        .cold_restart()
        .context("materialize the server from the bucket alone")?;
    oracle::check(cluster, agents, "a cold restart from the bucket alone")
}

fn apply(
    cluster: &mut Cluster,
    agents: &mut [Agent],
    step: &Step,
    wal_writes_failing: bool,
) -> Result<()> {
    match step {
        Step::Commit {
            agent,
            files,
            description,
        } => {
            let outcome = agents[*agent].commit_files(files, description);
            tolerate_injected_failure(cluster, outcome, wal_writes_failing)?;
        }
        Step::Describe { agent, description } => {
            let outcome = agents[*agent].describe(description);
            tolerate_injected_failure(cluster, outcome, wal_writes_failing)?;
        }
        Step::ArmCasConflicts { count } => cluster.faults.set_index_cas_conflicts(*count),
        Step::StageObjectOnConflict { bytes } => cluster
            .faults
            .stage_object_on_index_conflict(Some(bytes.clone())),
        Step::FailWalWrites { count } => cluster.faults.fail_wal_writes(*count),
        Step::FailDerivedHeadWal(on) => cluster.faults.fail_derived_head_wal(*on),
        Step::ArmCrash(window) => cluster.faults.crash_at(Some(*window)),
        Step::Restart => cluster.restart().context("restart the server")?,
        Step::ColdRestart => cluster
            .cold_restart()
            .context("restart the server from the bucket alone")?,
    }
    Ok(())
}

/// A client error is expected when the server has stopped answering or when the
/// bucket is refusing WAL entries, and only then. Anything else is the failure
/// the simulation is looking for.
fn tolerate_injected_failure<T>(
    cluster: &Cluster,
    outcome: Result<T>,
    wal_writes_failing: bool,
) -> Result<()> {
    match outcome {
        Ok(_) => Ok(()),
        Err(err) if cluster.halted() => {
            tracing_note(&format!("client error after an injected crash: {err:#}"));
            Ok(())
        }
        Err(err) if wal_writes_failing => {
            tracing_note(&format!(
                "client error after an injected WAL write failure: {err:#}"
            ));
            Ok(())
        }
        Err(err) => Err(err.context("a client operation failed with no fault to explain it")),
    }
}

fn tracing_note(message: &str) {
    if std::env::var_os("TANDEM_DST_VERBOSE").is_some() {
        eprintln!("  {message}");
    }
}
