#!/usr/bin/env python3
"""Check repository documentation drift and regenerate its code inventory."""

from __future__ import annotations

import argparse
import glob
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote


ROOT = Path(__file__).resolve().parent.parent
INVENTORY = ROOT / "docs/generated/implementation.md"

ACTIVE_DOCS = {
    ROOT / "README.md",
    ROOT / "AGENTS.md",
    ROOT / "ARCHITECTURE.md",
    ROOT / "docs/README.md",
    ROOT / "docs/reliability.md",
    ROOT / "docs/testing.md",
    ROOT / "docs/operations.md",
    ROOT / "docs/benchmarks/README.md",
    ROOT / "docs/images/README.md",
    ROOT / ".agents/skills/release/SKILL.md",
    ROOT / ".agents/skills/distributed-smoke/SKILL.md",
}

RETIRED_PATHS = (
    "docs/design-docs/",
    "docs/exec-plans/",
    "docs/product-specs/",
    "qa/",
)

RETIRED_TERMS = {
    "Cap'n Proto": re.compile(r"cap(?:'|’)?n proto|capnp", re.IGNORECASE),
    "line-JSON": re.compile(r"line[- ]json", re.IGNORECASE),
    "raw TCP": re.compile(r"raw tcp", re.IGNORECASE),
    "slice-number planning": re.compile(r"\bslice\s*\d+", re.IGNORECASE),
}

MARKDOWN_LINK = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
INLINE_CODE = re.compile(r"`([^`\n]+)`")
REPO_PATH_START = re.compile(
    r"^(?:\.agents/|\.github/|benches/|docs/|scripts/|skills/|src/|tests/|"
    r"AGENTS\.md$|ARCHITECTURE\.md$|Cargo\.toml$|README\.md$)"
)


def kebab(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def enum_variants(source: str, enum_name: str) -> list[str]:
    match = re.search(rf"enum {re.escape(enum_name)} \{{(.*?)\n\}}", source, re.DOTALL)
    if not match:
        raise ValueError(f"cannot find enum {enum_name}")
    return [
        kebab(name)
        for name in re.findall(r"^    ([A-Z][A-Za-z0-9_]*)\s*\{", match.group(1), re.MULTILINE)
    ]


def implementation_inventory() -> str:
    main = (ROOT / "src/main.rs").read_text()
    http = (ROOT / "src/server/http.rs").read_text()

    commands = enum_variants(main, "Commands")
    server_commands = enum_variants(main, "ServerCommands")

    routes: list[tuple[str, str]] = []
    for path, handlers in re.findall(r'\.route\("([^"]+)",\s*([^\n]+)\)', http):
        methods = sorted({method.upper() for method in re.findall(r"\b(get|post|put|delete|patch)\s*\(", handlers)})
        routes.append((", ".join(methods), path))

    sources = sorted(
        path.relative_to(ROOT).as_posix() for path in (ROOT / "src").rglob("*.rs")
    )
    test_modules = sorted(
        path.relative_to(ROOT).as_posix()
        for directory in (ROOT / "tests/integration", ROOT / "tests/properties")
        for path in directory.glob("*.rs")
    )

    lines = [
        "# Implementation inventory",
        "",
        "> Generated by `python3 scripts/check_docs.py --update-inventory`.",
        "> Do not edit by hand. Descriptions and flags remain authoritative in generated CLI help.",
        "",
        "## Tandem-owned commands",
        "",
        *[f"- `tandem {command}`" for command in commands if command != "server"],
        *[f"- `tandem server {command}`" for command in server_commands],
        "",
        "All other accepted commands are dispatched to embedded jj.",
        "",
        "## Authenticated repository routes",
        "",
        "| Method | Path |",
        "| --- | --- |",
        *[f"| {methods} | `{path}` |" for methods, path in routes],
        "",
        "## Source modules",
        "",
        *[f"- `{path}`" for path in sources],
        "",
        "## Generated test modules",
        "",
        *[f"- `{path}`" for path in test_modules],
        "",
        "The test binaries are `tests/dst.rs`, `tests/integration.rs`, and",
        "`tests/properties.rs`; unit tests remain beside their source modules.",
        "",
    ]
    return "\n".join(lines)


def markdown_files() -> list[Path]:
    ignored = {".git", ".jj", "target"}
    return sorted(
        path
        for path in ROOT.rglob("*.md")
        if not any(part in ignored for part in path.relative_to(ROOT).parts)
    )


def local_target(raw: str) -> str | None:
    raw = raw.strip()
    if raw.startswith("<") and raw.endswith(">"):
        raw = raw[1:-1]
    else:
        raw = raw.split(maxsplit=1)[0]
    if re.match(r"^(?:[a-z][a-z0-9+.-]*:|#)", raw, re.IGNORECASE):
        return None
    return unquote(raw.split("#", 1)[0].split("?", 1)[0])


def check_links(errors: list[str]) -> None:
    for document in markdown_files():
        for match in MARKDOWN_LINK.finditer(document.read_text()):
            target = local_target(match.group(1))
            if not target:
                continue
            resolved = (document.parent / target).resolve()
            if not resolved.exists():
                errors.append(
                    f"{document.relative_to(ROOT)}: broken local link {match.group(1)!r}"
                )


def path_exists(document: Path, token: str) -> bool:
    token = token.rstrip(".,;:")
    if "::" in token:
        token = token.split("::", 1)[0]
    candidates = [ROOT / token, document.parent / token]
    if any(char in token for char in "*?["):
        return any(glob.glob(str(candidate)) for candidate in candidates)
    return any(candidate.exists() for candidate in candidates)


def check_inline_paths(errors: list[str]) -> None:
    for document in ACTIVE_DOCS:
        if not document.exists():
            errors.append(f"missing active document: {document.relative_to(ROOT)}")
            continue
        for code in INLINE_CODE.findall(document.read_text()):
            token = code.strip()
            if " " in token or not REPO_PATH_START.match(token):
                continue
            if not path_exists(document, token):
                errors.append(
                    f"{document.relative_to(ROOT)}: reference to missing repo path {token!r}"
                )


def tracked_files() -> list[Path]:
    output = subprocess.run(
        ["jj", "file", "list"], cwd=ROOT, check=True, text=True, capture_output=True
    ).stdout
    return [ROOT / line for line in output.splitlines() if line]


def check_retired_paths(errors: list[str]) -> None:
    for path in tracked_files():
        if path.resolve() == Path(__file__).resolve():
            continue
        if path.suffix not in {".md", ".rs", ".toml", ".yaml", ".yml", ".sh", ".py"}:
            continue
        text = path.read_text(errors="replace")
        for retired in RETIRED_PATHS:
            if retired in text:
                errors.append(
                    f"{path.relative_to(ROOT)}: references deleted path prefix {retired!r}"
                )


def check_retired_terms(errors: list[str]) -> None:
    for document in ACTIVE_DOCS:
        if not document.exists():
            continue
        text = document.read_text()
        for label, pattern in RETIRED_TERMS.items():
            if pattern.search(text):
                errors.append(
                    f"{document.relative_to(ROOT)}: retired active-doc terminology: {label}"
                )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--update-inventory",
        action="store_true",
        help="rewrite the generated implementation inventory before checking",
    )
    args = parser.parse_args()

    expected = implementation_inventory()
    if args.update_inventory:
        INVENTORY.parent.mkdir(parents=True, exist_ok=True)
        INVENTORY.write_text(expected)

    errors: list[str] = []
    if not INVENTORY.exists() or INVENTORY.read_text() != expected:
        errors.append(
            "docs/generated/implementation.md is stale; run "
            "python3 scripts/check_docs.py --update-inventory"
        )

    check_links(errors)
    check_inline_paths(errors)
    check_retired_paths(errors)
    check_retired_terms(errors)

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    print(f"documentation checks passed ({len(markdown_files())} Markdown files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
